BEGIN;

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deduplication_key TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    recipient_ids BIGINT[] NOT NULL,
    payload JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    locked_until TIMESTAMPTZ,
    locked_by TEXT,
    published_at TIMESTAMPTZ,
    last_error TEXT,
    CHECK (cardinality(recipient_ids) > 0),
    CHECK ((locked_until IS NULL) = (locked_by IS NULL))
);

CREATE INDEX outbox_events_pending_idx
    ON outbox_events (available_at, id)
    WHERE published_at IS NULL;

COMMIT;
