BEGIN;

CREATE TABLE user_reputation (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    rating NUMERIC(3, 2),
    reviews_count INTEGER NOT NULL DEFAULT 0 CHECK (reviews_count >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    CHECK ((reviews_count = 0 AND rating IS NULL) OR
           (reviews_count > 0 AND rating IS NOT NULL))
);

INSERT INTO user_reputation (user_id)
SELECT id FROM users;

CREATE TABLE user_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id BIGINT NOT NULL REFERENCES chains(id),
    author_user_id BIGINT NOT NULL REFERENCES users(id),
    target_user_id BIGINT NOT NULL REFERENCES users(id),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (author_user_id <> target_user_id),
    CHECK (review_text IS NULL OR
           (length(review_text) BETWEEN 1 AND 1000 AND review_text = trim(review_text))),
    UNIQUE (chain_id, author_user_id, target_user_id)
);

CREATE INDEX user_reviews_target_page_idx
    ON user_reviews (target_user_id, id DESC);

COMMIT;
