CREATE EXTENSION IF NOT EXISTS vector;

CREATE TYPE chain_status AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');
CREATE TYPE participant_status AS ENUM ('WAITING', 'APPROVED', 'DECLINED');

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    rating NUMERIC(3, 2) NOT NULL DEFAULT 0 CHECK (rating >= 0 AND rating <= 5)
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    offer_title TEXT NOT NULL CHECK (length(trim(offer_title)) > 0),
    offer_description TEXT,
    offer_category TEXT,
    want_description TEXT,
    want_category TEXT,
    offer_embedding vector(1024) NOT NULL,
    want_embedding vector(1024) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id, user_id)
);

CREATE INDEX items_user_id_idx ON items (user_id);
CREATE INDEX items_offer_embedding_cosine_idx
    ON items USING hnsw (offer_embedding vector_cosine_ops);

CREATE TABLE chains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status chain_status NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE chain_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id BIGINT NOT NULL REFERENCES chains (id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id),
    next_item_id BIGINT REFERENCES items (id),
    status participant_status NOT NULL DEFAULT 'WAITING',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (item_id, user_id) REFERENCES items (id, user_id),
    CHECK (next_item_id IS NULL OR next_item_id <> item_id),
    UNIQUE (chain_id, item_id),
    UNIQUE (chain_id, user_id)
);

CREATE INDEX chain_items_item_id_idx ON chain_items (item_id);
CREATE INDEX chain_items_next_item_id_idx ON chain_items (next_item_id);
