CREATE TYPE user_role AS ENUM ('USER', 'ADMIN');
CREATE TYPE delivery_status AS ENUM ('AWAITING_PVZ', 'AT_PVZ', 'IN_DELIVERY');

ALTER TABLE users
    ADD COLUMN role user_role NOT NULL DEFAULT 'USER';

-- Конфликтующий реальный аккаунт не получает права администратора: обновление
-- разрешено только для зарезервированной демонстрационной учётной записи.
INSERT INTO users (username, phone, role)
VALUES ('ПВЗ Администратор (demo)', '+79009999999', 'ADMIN')
ON CONFLICT (phone) DO UPDATE
SET role = 'ADMIN'
WHERE users.username = 'ПВЗ Администратор (demo)';

ALTER TABLE chain_items
    ADD COLUMN delivery_status delivery_status NOT NULL DEFAULT 'AWAITING_PVZ',
    ADD COLUMN delivery_updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX chain_items_delivery_queue_idx
    ON chain_items (delivery_status, id);

CREATE TABLE admin_delivery_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_item_id BIGINT NOT NULL REFERENCES chain_items (id) ON DELETE CASCADE,
    actor_user_id BIGINT NOT NULL REFERENCES users (id),
    from_status delivery_status NOT NULL,
    to_status delivery_status NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (from_status <> to_status),
    UNIQUE (chain_item_id, to_status)
);

CREATE INDEX admin_delivery_events_chain_item_id_idx
    ON admin_delivery_events (chain_item_id, occurred_at);
