CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id BIGINT NOT NULL REFERENCES chains (id) ON DELETE CASCADE,
    sender_user_id BIGINT NOT NULL REFERENCES users (id),
    recipient_user_id BIGINT NOT NULL REFERENCES users (id),
    client_message_id VARCHAR(64) NOT NULL,
    message_text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (sender_user_id <> recipient_user_id),
    CHECK (length(trim(client_message_id)) BETWEEN 1 AND 64),
    CHECK (length(trim(message_text)) BETWEEN 1 AND 2000),
    FOREIGN KEY (chain_id, sender_user_id)
        REFERENCES chain_items (chain_id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (chain_id, recipient_user_id)
        REFERENCES chain_items (chain_id, user_id) ON DELETE CASCADE,
    UNIQUE (chain_id, sender_user_id, recipient_user_id, client_message_id)
);

CREATE INDEX chat_messages_sender_thread_idx
    ON chat_messages (chain_id, sender_user_id, recipient_user_id, id);

CREATE INDEX chat_messages_recipient_thread_idx
    ON chat_messages (chain_id, recipient_user_id, sender_user_id, id);

CREATE INDEX chain_items_chat_user_id_chain_id_idx
    ON chain_items (user_id, chain_id);

CREATE TABLE chat_read_states (
    chain_id BIGINT NOT NULL REFERENCES chains (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id),
    counterpart_user_id BIGINT NOT NULL REFERENCES users (id),
    last_read_message_id BIGINT NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (chain_id, user_id, counterpart_user_id),
    CHECK (user_id <> counterpart_user_id),
    FOREIGN KEY (chain_id, user_id)
        REFERENCES chain_items (chain_id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (chain_id, counterpart_user_id)
        REFERENCES chain_items (chain_id, user_id) ON DELETE CASCADE
);
