CREATE TYPE support_message_sender_type AS ENUM ('USER', 'MODERATOR', 'SYSTEM');

CREATE TABLE support_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE support_thread_moderators (
    thread_id BIGINT NOT NULL REFERENCES support_threads (id) ON DELETE CASCADE,
    moderator_id BIGINT NOT NULL REFERENCES users (id),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (thread_id, moderator_id)
);

CREATE TABLE support_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL REFERENCES support_threads (id) ON DELETE CASCADE,
    sender_type support_message_sender_type NOT NULL,
    sender_user_id BIGINT REFERENCES users (id),
    client_message_id VARCHAR(64),
    message_text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (length(trim(message_text)) BETWEEN 1 AND 2000),
    CHECK (
        (sender_type = 'SYSTEM' AND sender_user_id IS NULL AND client_message_id IS NULL)
        OR
        (sender_type <> 'SYSTEM' AND sender_user_id IS NOT NULL AND length(trim(client_message_id)) BETWEEN 1 AND 64)
    )
);

CREATE UNIQUE INDEX support_messages_client_id_idx
    ON support_messages (thread_id, sender_user_id, client_message_id)
    WHERE sender_user_id IS NOT NULL;
CREATE INDEX support_messages_thread_id_idx ON support_messages (thread_id, id);

CREATE TABLE support_read_states (
    thread_id BIGINT NOT NULL REFERENCES support_threads (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    last_read_message_id BIGINT NOT NULL REFERENCES support_messages (id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (thread_id, user_id)
);

CREATE FUNCTION create_support_thread_for_user() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    new_thread_id BIGINT;
BEGIN
    INSERT INTO support_threads (user_id) VALUES (NEW.id) RETURNING id INTO new_thread_id;
    INSERT INTO support_messages (thread_id, sender_type, message_text)
    VALUES (new_thread_id, 'SYSTEM', 'Добро пожаловать в «Авито Обмен». Здесь можно задать вопрос службе поддержки или сообщить о проблеме.');
    RETURN NEW;
END;
$$;

CREATE TRIGGER users_create_support_thread
AFTER INSERT ON users
FOR EACH ROW EXECUTE FUNCTION create_support_thread_for_user();

DO $$
DECLARE
    user_row RECORD;
    new_thread_id BIGINT;
BEGIN
    FOR user_row IN SELECT id FROM users ORDER BY id LOOP
        INSERT INTO support_threads (user_id) VALUES (user_row.id)
        ON CONFLICT (user_id) DO NOTHING
        RETURNING id INTO new_thread_id;
        IF new_thread_id IS NOT NULL THEN
            INSERT INTO support_messages (thread_id, sender_type, message_text)
            VALUES (new_thread_id, 'SYSTEM', 'Добро пожаловать в «Авито Обмен». Здесь можно задать вопрос службе поддержки или сообщить о проблеме.');
        END IF;
        new_thread_id := NULL;
    END LOOP;
END
$$;
