DROP TABLE IF EXISTS chain_items;
DROP TABLE IF EXISTS chains;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS participant_status;
DROP TYPE IF EXISTS chain_status;
DROP EXTENSION IF EXISTS vector;
