CREATE TYPE user_report_reason AS ENUM ('item', 'noshow', 'rude', 'fraud', 'other');

CREATE TABLE user_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    target_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    chain_id BIGINT REFERENCES chains (id) ON DELETE SET NULL,
    reason user_report_reason NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (reporter_user_id <> target_user_id),
    CHECK (comment IS NULL OR length(comment) <= 1000),
    CHECK (reason <> 'other' OR comment IS NOT NULL),
    UNIQUE NULLS NOT DISTINCT (reporter_user_id, target_user_id, chain_id)
);

CREATE INDEX user_reports_target_user_id_created_at_idx
    ON user_reports (target_user_id, created_at DESC);
