CREATE TYPE item_status AS ENUM ('ANALYZING', 'MATCHING', 'LOCKED');

CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    embedding vector(1024) NOT NULL
);

ALTER TABLE users
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE items
    ADD COLUMN status item_status,
    ADD COLUMN image_urls TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ALTER COLUMN offer_embedding DROP NOT NULL,
    ALTER COLUMN want_embedding DROP NOT NULL;

UPDATE items
SET status = CASE
    WHEN offer_embedding IS NOT NULL AND want_embedding IS NOT NULL THEN 'MATCHING'::item_status
    ELSE 'ANALYZING'::item_status
END;

ALTER TABLE items
    ALTER COLUMN status SET DEFAULT 'ANALYZING',
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE items
    ADD CONSTRAINT items_image_urls_limit CHECK (cardinality(image_urls) <= 10);

CREATE INDEX items_status_id_idx ON items (status, id);

CREATE INDEX categories_embedding_cosine_idx
    ON categories USING hnsw (embedding vector_cosine_ops);

ALTER TABLE chains
    ADD COLUMN expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '24 hours'),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX chains_pending_expiration_idx
    ON chains (expires_at)
    WHERE status = 'PENDING';

CREATE INDEX chain_items_chain_id_idx ON chain_items (chain_id);
