BEGIN;

CREATE TYPE report_status AS ENUM ('open', 'resolved', 'rejected');
CREATE TYPE report_reason AS ENUM ('spam', 'abuse', 'other');
CREATE TYPE audit_action AS ENUM (
    'REPORT_ASSIGNED',
    'REPORT_RESOLVED',
    'REPORT_REJECTED',
    'USER_BLOCKED',
    'CHAIN_CANCELLED',
    'DELIVERY_STATUS_CHANGED'
);

-- Направленный персональный чёрный список. Для matching блокировка действует
-- симметрично, но хранится как направленное ребро (кто кого заблокировал).
CREATE TABLE user_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    blocked_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (blocker_user_id <> blocked_user_id),
    UNIQUE (blocker_user_id, blocked_user_id)
);

CREATE INDEX user_blocks_blocker_idx ON user_blocks (blocker_user_id, blocked_user_id);
CREATE INDEX user_blocks_blocked_idx ON user_blocks (blocked_user_id, blocker_user_id);

-- Жалоба на сообщение. Уникальна по паре (репортёр, сообщение); идемпотентна.
CREATE TABLE message_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL REFERENCES users (id),
    message_id BIGINT NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    reason report_reason NOT NULL,
    comment TEXT,
    status report_status NOT NULL DEFAULT 'open',
    assignee_user_id BIGINT REFERENCES users (id),
    decision_comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (reporter_user_id, message_id),
    CHECK (reason <> 'other' OR (comment IS NOT NULL AND length(btrim(comment)) BETWEEN 1 AND 1000)),
    CHECK (length(btrim(COALESCE(comment, ''))) <= 1000),
    CHECK (
        status = 'open'
        OR (decision_comment IS NOT NULL AND length(btrim(decision_comment)) BETWEEN 1 AND 1000)
    )
);

CREATE INDEX message_reports_queue_idx ON message_reports (status, reason, id);
CREATE INDEX message_reports_assignee_idx ON message_reports (assignee_user_id, id);
CREATE INDEX message_reports_reporter_idx ON message_reports (reporter_user_id, id);

-- Append-only аудит административных действий.
CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL REFERENCES users (id),
    action audit_action NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX admin_audit_log_newest_idx ON admin_audit_log (id DESC);
CREATE INDEX admin_audit_log_action_idx ON admin_audit_log (action, id DESC);

-- Расширение словаря причин отклонения цепочки значением 'blocked'.
ALTER TABLE chain_rejections DROP CONSTRAINT chain_rejections_reason_check;
ALTER TABLE chain_rejections ADD CONSTRAINT chain_rejections_reason_check
    CHECK (reason IN (
        'declined',
        'expired',
        'item_unavailable',
        'item_changed',
        'item_withdrawn',
        'blocked',
        'unknown'
    ));

COMMIT;
