// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"
)

const completeAdminChain = `-- name: CompleteAdminChain :execrows
UPDATE chains
SET status = 'COMPLETED',
    updated_at = now()
WHERE id = $1
  AND status = 'ACCEPTED'
`

func (q *Queries) CompleteAdminChain(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeAdminChain, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnreceivedAdminDeliveries = `-- name: CountUnreceivedAdminDeliveries :one
SELECT count(*)
FROM chain_items AS delivery
WHERE delivery.chain_id = $1
  AND delivery.delivery_status <> 'RECEIVED'
`

func (q *Queries) CountUnreceivedAdminDeliveries(ctx context.Context, chainID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreceivedAdminDeliveries, chainID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminDeliveryEvent = `-- name: CreateAdminDeliveryEvent :exec
INSERT INTO admin_delivery_events (
    chain_item_id,
    actor_user_id,
    from_status,
    to_status
)
VALUES (
    $1,
    $2,
    $3::delivery_status,
    $4::delivery_status
)
`

type CreateAdminDeliveryEventParams struct {
	DeliveryID int64          `json:"delivery_id"`
	ActorID    int64          `json:"actor_id"`
	FromStatus DeliveryStatus `json:"from_status"`
	ToStatus   DeliveryStatus `json:"to_status"`
}

func (q *Queries) CreateAdminDeliveryEvent(ctx context.Context, arg CreateAdminDeliveryEventParams) error {
	_, err := q.db.ExecContext(ctx, createAdminDeliveryEvent,
		arg.DeliveryID,
		arg.ActorID,
		arg.FromStatus,
		arg.ToStatus,
	)
	return err
}

const findAdminDeliveryChain = `-- name: FindAdminDeliveryChain :one
SELECT delivery.chain_id
FROM chain_items AS delivery
WHERE delivery.id = $1
`

func (q *Queries) FindAdminDeliveryChain(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, findAdminDeliveryChain, id)
	var chain_id int64
	err := row.Scan(&chain_id)
	return chain_id, err
}

const getAdminDelivery = `-- name: GetAdminDelivery :one
SELECT delivery.id,
       delivery.chain_id,
       delivery.item_id,
       item.offer_title AS item_title,
       sender.id AS sender_id,
       sender.username AS sender_username,
       recipient.id AS recipient_id,
       recipient.username AS recipient_username,
       delivery.delivery_status::text AS delivery_status,
       delivery.delivery_updated_at
FROM chain_items AS delivery
JOIN items AS item ON item.id = delivery.item_id
JOIN users AS sender ON sender.id = delivery.user_id
JOIN chain_items AS recipient_leg
  ON recipient_leg.chain_id = delivery.chain_id
 AND recipient_leg.next_item_id = delivery.item_id
JOIN users AS recipient ON recipient.id = recipient_leg.user_id
WHERE delivery.id = $1
`

type GetAdminDeliveryRow struct {
	ID                int64     `json:"id"`
	ChainID           int64     `json:"chain_id"`
	ItemID            int64     `json:"item_id"`
	ItemTitle         string    `json:"item_title"`
	SenderID          int64     `json:"sender_id"`
	SenderUsername    string    `json:"sender_username"`
	RecipientID       int64     `json:"recipient_id"`
	RecipientUsername string    `json:"recipient_username"`
	DeliveryStatus    string    `json:"delivery_status"`
	DeliveryUpdatedAt time.Time `json:"delivery_updated_at"`
}

func (q *Queries) GetAdminDelivery(ctx context.Context, id int64) (GetAdminDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminDelivery, id)
	var i GetAdminDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.ItemID,
		&i.ItemTitle,
		&i.SenderID,
		&i.SenderUsername,
		&i.RecipientID,
		&i.RecipientUsername,
		&i.DeliveryStatus,
		&i.DeliveryUpdatedAt,
	)
	return i, err
}

const isAdminUser = `-- name: IsAdminUser :one
SELECT app_user.role = 'ADMIN'::user_role AS is_admin
FROM users AS app_user
WHERE app_user.id = $1
FOR SHARE
`

func (q *Queries) IsAdminUser(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAdminUser, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listAdminDeliveries = `-- name: ListAdminDeliveries :many
SELECT delivery.id,
       delivery.chain_id,
       delivery.item_id,
       item.offer_title AS item_title,
       sender.id AS sender_id,
       sender.username AS sender_username,
       recipient.id AS recipient_id,
       recipient.username AS recipient_username,
       delivery.delivery_status::text AS delivery_status,
       delivery.delivery_updated_at
FROM chain_items AS delivery
JOIN chains AS chain ON chain.id = delivery.chain_id
JOIN items AS item ON item.id = delivery.item_id
JOIN users AS sender ON sender.id = delivery.user_id
JOIN chain_items AS recipient_leg
  ON recipient_leg.chain_id = delivery.chain_id
 AND recipient_leg.next_item_id = delivery.item_id
JOIN users AS recipient ON recipient.id = recipient_leg.user_id
WHERE chain.status IN ('ACCEPTED', 'COMPLETED')
  AND item.status = 'LOCKED'
  AND delivery.id > $1
  AND ($2::text = ''
       OR delivery.delivery_status::text = $2::text)
ORDER BY delivery.id
LIMIT $3
`

type ListAdminDeliveriesParams struct {
	AfterID        int64  `json:"after_id"`
	DeliveryStatus string `json:"delivery_status"`
	PageSize       int32  `json:"page_size"`
}

type ListAdminDeliveriesRow struct {
	ID                int64     `json:"id"`
	ChainID           int64     `json:"chain_id"`
	ItemID            int64     `json:"item_id"`
	ItemTitle         string    `json:"item_title"`
	SenderID          int64     `json:"sender_id"`
	SenderUsername    string    `json:"sender_username"`
	RecipientID       int64     `json:"recipient_id"`
	RecipientUsername string    `json:"recipient_username"`
	DeliveryStatus    string    `json:"delivery_status"`
	DeliveryUpdatedAt time.Time `json:"delivery_updated_at"`
}

func (q *Queries) ListAdminDeliveries(ctx context.Context, arg ListAdminDeliveriesParams) ([]ListAdminDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminDeliveries, arg.AfterID, arg.DeliveryStatus, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminDeliveriesRow
	for rows.Next() {
		var i ListAdminDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.ItemID,
			&i.ItemTitle,
			&i.SenderID,
			&i.SenderUsername,
			&i.RecipientID,
			&i.RecipientUsername,
			&i.DeliveryStatus,
			&i.DeliveryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminChain = `-- name: LockAdminChain :one
SELECT chain.status::text AS chain_status
FROM chains AS chain
WHERE chain.id = $1
FOR UPDATE
`

func (q *Queries) LockAdminChain(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, lockAdminChain, id)
	var chain_status string
	err := row.Scan(&chain_status)
	return chain_status, err
}

const lockAdminDelivery = `-- name: LockAdminDelivery :one
SELECT delivery.delivery_status::text AS delivery_status,
       item.status::text AS item_status
FROM chain_items AS delivery
JOIN items AS item ON item.id = delivery.item_id
WHERE delivery.id = $1
FOR UPDATE OF delivery, item
`

type LockAdminDeliveryRow struct {
	DeliveryStatus string `json:"delivery_status"`
	ItemStatus     string `json:"item_status"`
}

func (q *Queries) LockAdminDelivery(ctx context.Context, id int64) (LockAdminDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, lockAdminDelivery, id)
	var i LockAdminDeliveryRow
	err := row.Scan(&i.DeliveryStatus, &i.ItemStatus)
	return i, err
}

const lockRecipientDelivery = `-- name: LockRecipientDelivery :one
SELECT delivery.id,
       delivery.delivery_status::text AS delivery_status,
       item.status::text AS item_status
FROM chain_items AS recipient_leg
JOIN chain_items AS delivery
  ON delivery.chain_id = recipient_leg.chain_id
 AND delivery.item_id = recipient_leg.next_item_id
JOIN items AS item ON item.id = delivery.item_id
WHERE recipient_leg.chain_id = $1
  AND recipient_leg.user_id = $2
FOR UPDATE OF delivery, item
`

type LockRecipientDeliveryParams struct {
	ChainID     int64 `json:"chain_id"`
	RecipientID int64 `json:"recipient_id"`
}

type LockRecipientDeliveryRow struct {
	ID             int64  `json:"id"`
	DeliveryStatus string `json:"delivery_status"`
	ItemStatus     string `json:"item_status"`
}

func (q *Queries) LockRecipientDelivery(ctx context.Context, arg LockRecipientDeliveryParams) (LockRecipientDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, lockRecipientDelivery, arg.ChainID, arg.RecipientID)
	var i LockRecipientDeliveryRow
	err := row.Scan(&i.ID, &i.DeliveryStatus, &i.ItemStatus)
	return i, err
}

const updateAdminDeliveryStatus = `-- name: UpdateAdminDeliveryStatus :exec
UPDATE chain_items
SET delivery_status = $1::delivery_status,
    delivery_updated_at = now()
WHERE id = $2
`

type UpdateAdminDeliveryStatusParams struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	DeliveryID     int64          `json:"delivery_id"`
}

func (q *Queries) UpdateAdminDeliveryStatus(ctx context.Context, arg UpdateAdminDeliveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminDeliveryStatus, arg.DeliveryStatus, arg.DeliveryID)
	return err
}
