// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO admin_audit_log (admin_user_id, action, target_type, target_id, metadata)
VALUES (
    $1,
    $2::audit_action,
    $3,
    $4,
    $5
)
`

type InsertAuditLogParams struct {
	AdminID    int64           `json:"admin_id"`
	Action     AuditAction     `json:"action"`
	TargetType string          `json:"target_type"`
	TargetID   int64           `json:"target_id"`
	Metadata   json.RawMessage `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT log.id,
       log.admin_user_id,
       admin.username AS admin_username,
       log.action::text AS action,
       log.target_type,
       log.target_id,
       log.metadata,
       log.created_at
FROM admin_audit_log AS log
JOIN users AS admin ON admin.id = log.admin_user_id
WHERE ($1::bigint IS NULL OR log.id < $1::bigint)
  AND ($2::text = '' OR log.action::text = $2::text)
  AND ($3::bigint = 0 OR log.admin_user_id = $3::bigint)
  AND ($4::text = '' OR log.target_type = $4::text)
ORDER BY log.id DESC
LIMIT $5
`

type ListAuditLogParams struct {
	BeforeID   sql.NullInt64 `json:"before_id"`
	Action     string        `json:"action"`
	AdminID    int64         `json:"admin_id"`
	TargetType string        `json:"target_type"`
	PageSize   int32         `json:"page_size"`
}

type ListAuditLogRow struct {
	ID            int64           `json:"id"`
	AdminUserID   int64           `json:"admin_user_id"`
	AdminUsername string          `json:"admin_username"`
	Action        string          `json:"action"`
	TargetType    string          `json:"target_type"`
	TargetID      int64           `json:"target_id"`
	Metadata      json.RawMessage `json:"metadata"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog,
		arg.BeforeID,
		arg.Action,
		arg.AdminID,
		arg.TargetType,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogRow
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.AdminUsername,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
