// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocklist.sql

package db

import (
	"context"
	"time"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks (blocker_user_id, blocked_user_id)
VALUES ($1, $2)
ON CONFLICT (blocker_user_id, blocked_user_id) DO NOTHING
`

type BlockUserParams struct {
	BlockerID int64 `json:"blocker_id"`
	BlockedID int64 `json:"blocked_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.ExecContext(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const getUserBlock = `-- name: GetUserBlock :one
SELECT user_blocks.id AS block_id,
       blocked.id AS blocked_user_id,
       blocked.username AS blocked_username,
       user_blocks.created_at
FROM user_blocks
JOIN users AS blocked ON blocked.id = user_blocks.blocked_user_id
WHERE user_blocks.blocker_user_id = $1
  AND user_blocks.blocked_user_id = $2
`

type GetUserBlockParams struct {
	BlockerID int64 `json:"blocker_id"`
	BlockedID int64 `json:"blocked_id"`
}

type GetUserBlockRow struct {
	BlockID         int64     `json:"block_id"`
	BlockedUserID   int64     `json:"blocked_user_id"`
	BlockedUsername string    `json:"blocked_username"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) GetUserBlock(ctx context.Context, arg GetUserBlockParams) (GetUserBlockRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBlock, arg.BlockerID, arg.BlockedID)
	var i GetUserBlockRow
	err := row.Scan(
		&i.BlockID,
		&i.BlockedUserID,
		&i.BlockedUsername,
		&i.CreatedAt,
	)
	return i, err
}

const listUserBlocks = `-- name: ListUserBlocks :many
SELECT user_blocks.id AS block_id,
       blocked.id AS blocked_user_id,
       blocked.username AS blocked_username,
       user_blocks.created_at
FROM user_blocks
JOIN users AS blocked ON blocked.id = user_blocks.blocked_user_id
WHERE user_blocks.blocker_user_id = $1
  AND user_blocks.id > $2
ORDER BY user_blocks.id
LIMIT $3
`

type ListUserBlocksParams struct {
	BlockerID int64 `json:"blocker_id"`
	AfterID   int64 `json:"after_id"`
	PageSize  int32 `json:"page_size"`
}

type ListUserBlocksRow struct {
	BlockID         int64     `json:"block_id"`
	BlockedUserID   int64     `json:"blocked_user_id"`
	BlockedUsername string    `json:"blocked_username"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) ListUserBlocks(ctx context.Context, arg ListUserBlocksParams) ([]ListUserBlocksRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserBlocks, arg.BlockerID, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserBlocksRow
	for rows.Next() {
		var i ListUserBlocksRow
		if err := rows.Scan(
			&i.BlockID,
			&i.BlockedUserID,
			&i.BlockedUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :execrows
DELETE FROM user_blocks
WHERE blocker_user_id = $1
  AND blocked_user_id = $2
`

type UnblockUserParams struct {
	BlockerID int64 `json:"blocker_id"`
	BlockedID int64 `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE id = $1
) AS exists
`

func (q *Queries) UserExists(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
