// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"
)

const chatMessageBelongsToThread = `-- name: ChatMessageBelongsToThread :one
SELECT EXISTS (
    SELECT 1
    FROM chat_messages AS message
    WHERE message.id = $1
      AND message.item_id = $2
      AND (
          (message.sender_user_id = $3 AND message.recipient_user_id = $4)
          OR
          (message.sender_user_id = $4 AND message.recipient_user_id = $3)
      )
)
`

type ChatMessageBelongsToThreadParams struct {
	MessageID     int64 `json:"message_id"`
	ItemID        int64 `json:"item_id"`
	ActorID       int64 `json:"actor_id"`
	CounterpartID int64 `json:"counterpart_id"`
}

func (q *Queries) ChatMessageBelongsToThread(ctx context.Context, arg ChatMessageBelongsToThreadParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, chatMessageBelongsToThread,
		arg.MessageID,
		arg.ItemID,
		arg.ActorID,
		arg.CounterpartID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUnreadChatMessages = `-- name: CountUnreadChatMessages :one
SELECT count(*)::bigint
FROM chat_messages AS message
WHERE message.item_id = $1
  AND message.sender_user_id = $2
  AND message.recipient_user_id = $3
  AND message.id > $4
`

type CountUnreadChatMessagesParams struct {
	ItemID            int64 `json:"item_id"`
	CounterpartID     int64 `json:"counterpart_id"`
	ActorID           int64 `json:"actor_id"`
	LastReadMessageID int64 `json:"last_read_message_id"`
}

func (q *Queries) CountUnreadChatMessages(ctx context.Context, arg CountUnreadChatMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadChatMessages,
		arg.ItemID,
		arg.CounterpartID,
		arg.ActorID,
		arg.LastReadMessageID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getChatAccessForShare = `-- name: GetChatAccessForShare :one
SELECT COALESCE(BOOL_OR(
           owner.user_id = $1
           OR recipient.user_id = $1
       ), false)::boolean AS is_actor_participant,
       COALESCE(BOOL_OR(
           owner.user_id = $2
           OR recipient.user_id = $2
       ), false)::boolean AS is_counterpart_participant,
       COALESCE(MIN(owner.chain_id) FILTER (WHERE
           (owner.user_id = $1 AND recipient.user_id = $2)
           OR (owner.user_id = $2 AND recipient.user_id = $1)
       ), 0)::bigint AS access_chain_id
FROM items AS topic_item
LEFT JOIN chain_items AS owner ON owner.item_id = topic_item.id
LEFT JOIN chain_items AS recipient
  ON recipient.chain_id = owner.chain_id
 AND recipient.next_item_id = owner.item_id
WHERE topic_item.id = $3
GROUP BY topic_item.id
`

type GetChatAccessForShareParams struct {
	ActorID       int64 `json:"actor_id"`
	CounterpartID int64 `json:"counterpart_id"`
	ItemID        int64 `json:"item_id"`
}

type GetChatAccessForShareRow struct {
	IsActorParticipant       bool  `json:"is_actor_participant"`
	IsCounterpartParticipant bool  `json:"is_counterpart_participant"`
	AccessChainID            int64 `json:"access_chain_id"`
}

func (q *Queries) GetChatAccessForShare(ctx context.Context, arg GetChatAccessForShareParams) (GetChatAccessForShareRow, error) {
	row := q.db.QueryRowContext(ctx, getChatAccessForShare, arg.ActorID, arg.CounterpartID, arg.ItemID)
	var i GetChatAccessForShareRow
	err := row.Scan(&i.IsActorParticipant, &i.IsCounterpartParticipant, &i.AccessChainID)
	return i, err
}

const getChatMessage = `-- name: GetChatMessage :one
SELECT message.id,
       message.item_id,
       message.chain_id AS origin_chain_id,
       sender.id AS sender_user_id,
       sender.username AS sender_username,
       recipient.id AS recipient_user_id,
       recipient.username AS recipient_username,
       message.client_message_id,
       message.message_text,
       message.created_at
FROM chat_messages AS message
JOIN users AS sender ON sender.id = message.sender_user_id
JOIN users AS recipient ON recipient.id = message.recipient_user_id
WHERE message.id = $1
`

type GetChatMessageRow struct {
	ID                int64     `json:"id"`
	ItemID            int64     `json:"item_id"`
	OriginChainID     int64     `json:"origin_chain_id"`
	SenderUserID      int64     `json:"sender_user_id"`
	SenderUsername    string    `json:"sender_username"`
	RecipientUserID   int64     `json:"recipient_user_id"`
	RecipientUsername string    `json:"recipient_username"`
	ClientMessageID   string    `json:"client_message_id"`
	MessageText       string    `json:"message_text"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) GetChatMessage(ctx context.Context, messageID int64) (GetChatMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getChatMessage, messageID)
	var i GetChatMessageRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.OriginChainID,
		&i.SenderUserID,
		&i.SenderUsername,
		&i.RecipientUserID,
		&i.RecipientUsername,
		&i.ClientMessageID,
		&i.MessageText,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessageByClientID = `-- name: GetChatMessageByClientID :one
SELECT message.id,
       message.item_id,
       message.chain_id AS origin_chain_id,
       sender.id AS sender_user_id,
       sender.username AS sender_username,
       recipient.id AS recipient_user_id,
       recipient.username AS recipient_username,
       message.client_message_id,
       message.message_text,
       message.created_at
FROM chat_messages AS message
JOIN users AS sender ON sender.id = message.sender_user_id
JOIN users AS recipient ON recipient.id = message.recipient_user_id
WHERE message.item_id = $1
  AND message.sender_user_id = $2
  AND message.recipient_user_id = $3
  AND message.client_message_id = $4
`

type GetChatMessageByClientIDParams struct {
	ItemID          int64  `json:"item_id"`
	SenderUserID    int64  `json:"sender_user_id"`
	RecipientUserID int64  `json:"recipient_user_id"`
	ClientMessageID string `json:"client_message_id"`
}

type GetChatMessageByClientIDRow struct {
	ID                int64     `json:"id"`
	ItemID            int64     `json:"item_id"`
	OriginChainID     int64     `json:"origin_chain_id"`
	SenderUserID      int64     `json:"sender_user_id"`
	SenderUsername    string    `json:"sender_username"`
	RecipientUserID   int64     `json:"recipient_user_id"`
	RecipientUsername string    `json:"recipient_username"`
	ClientMessageID   string    `json:"client_message_id"`
	MessageText       string    `json:"message_text"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) GetChatMessageByClientID(ctx context.Context, arg GetChatMessageByClientIDParams) (GetChatMessageByClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChatMessageByClientID,
		arg.ItemID,
		arg.SenderUserID,
		arg.RecipientUserID,
		arg.ClientMessageID,
	)
	var i GetChatMessageByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.OriginChainID,
		&i.SenderUserID,
		&i.SenderUsername,
		&i.RecipientUserID,
		&i.RecipientUsername,
		&i.ClientMessageID,
		&i.MessageText,
		&i.CreatedAt,
	)
	return i, err
}

const insertChatMessage = `-- name: InsertChatMessage :one
INSERT INTO chat_messages (
    chain_id,
    item_id,
    sender_user_id,
    recipient_user_id,
    client_message_id,
    message_text
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (item_id, sender_user_id, recipient_user_id, client_message_id) DO NOTHING
RETURNING id
`

type InsertChatMessageParams struct {
	ChainID         int64  `json:"chain_id"`
	ItemID          int64  `json:"item_id"`
	SenderUserID    int64  `json:"sender_user_id"`
	RecipientUserID int64  `json:"recipient_user_id"`
	ClientMessageID string `json:"client_message_id"`
	MessageText     string `json:"message_text"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChatMessage,
		arg.ChainID,
		arg.ItemID,
		arg.SenderUserID,
		arg.RecipientUserID,
		arg.ClientMessageID,
		arg.MessageText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT message.id,
       message.item_id,
       message.chain_id AS origin_chain_id,
       sender.id AS sender_user_id,
       sender.username AS sender_username,
       recipient.id AS recipient_user_id,
       recipient.username AS recipient_username,
       message.client_message_id,
       message.message_text,
       message.created_at
FROM chat_messages AS message
JOIN users AS sender ON sender.id = message.sender_user_id
JOIN users AS recipient ON recipient.id = message.recipient_user_id
WHERE message.item_id = $1
  AND (
      (message.sender_user_id = $2 AND message.recipient_user_id = $3)
      OR
      (message.sender_user_id = $3 AND message.recipient_user_id = $2)
  )
  AND message.id > $4
ORDER BY message.id ASC
LIMIT $5
`

type ListChatMessagesParams struct {
	ItemID        int64 `json:"item_id"`
	ActorID       int64 `json:"actor_id"`
	CounterpartID int64 `json:"counterpart_id"`
	AfterID       int64 `json:"after_id"`
	ResultLimit   int32 `json:"result_limit"`
}

type ListChatMessagesRow struct {
	ID                int64     `json:"id"`
	ItemID            int64     `json:"item_id"`
	OriginChainID     int64     `json:"origin_chain_id"`
	SenderUserID      int64     `json:"sender_user_id"`
	SenderUsername    string    `json:"sender_username"`
	RecipientUserID   int64     `json:"recipient_user_id"`
	RecipientUsername string    `json:"recipient_username"`
	ClientMessageID   string    `json:"client_message_id"`
	MessageText       string    `json:"message_text"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ListChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages,
		arg.ItemID,
		arg.ActorID,
		arg.CounterpartID,
		arg.AfterID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesRow
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.OriginChainID,
			&i.SenderUserID,
			&i.SenderUsername,
			&i.RecipientUserID,
			&i.RecipientUsername,
			&i.ClientMessageID,
			&i.MessageText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatThreads = `-- name: ListChatThreads :many
WITH incoming_transfers AS (
    SELECT DISTINCT owner.item_id,
           owner.user_id AS counterpart_user_id
    FROM chain_items AS owner
    JOIN chain_items AS recipient
      ON recipient.chain_id = owner.chain_id
     AND recipient.next_item_id = owner.item_id
    WHERE recipient.user_id = $1
), messaged_transfers AS (
    SELECT DISTINCT message.item_id,
           CASE
               WHEN message.sender_user_id = $1 THEN message.recipient_user_id
               ELSE message.sender_user_id
           END AS counterpart_user_id
    FROM chat_messages AS message
    WHERE message.sender_user_id = $1
       OR message.recipient_user_id = $1
), transfers AS (
    SELECT item_id, counterpart_user_id FROM incoming_transfers
    UNION
    SELECT item_id, counterpart_user_id FROM messaged_transfers
)
SELECT topic_item.id AS item_id,
       topic_item.offer_title AS item_title,
       COALESCE(topic_item.image_urls[1], '')::text AS item_image_url,
       counterpart.id AS counterpart_user_id,
       counterpart.username AS counterpart_username,
       COALESCE(latest.id, 0)::bigint AS last_message_id,
       COALESCE(latest.origin_chain_id, 0)::bigint AS last_origin_chain_id,
       COALESCE(latest.sender_user_id, 0)::bigint AS last_sender_user_id,
       COALESCE(latest.sender_username, '')::text AS last_sender_username,
       COALESCE(latest.recipient_user_id, 0)::bigint AS last_recipient_user_id,
       COALESCE(latest.recipient_username, '')::text AS last_recipient_username,
       COALESCE(latest.client_message_id, '')::text AS last_client_message_id,
       COALESCE(latest.message_text, '')::text AS last_message_text,
       COALESCE(latest.created_at, TIMESTAMPTZ 'epoch') AS last_message_created_at,
       COALESCE(unread.unread_count, 0)::bigint AS unread_count
FROM transfers AS thread
JOIN items AS topic_item ON topic_item.id = thread.item_id
JOIN users AS counterpart ON counterpart.id = thread.counterpart_user_id
LEFT JOIN LATERAL (
    SELECT message.id,
           message.chain_id AS origin_chain_id,
           message.sender_user_id,
           sender.username AS sender_username,
           message.recipient_user_id,
           recipient.username AS recipient_username,
           message.client_message_id,
           message.message_text,
           message.created_at
    FROM chat_messages AS message
    JOIN users AS sender ON sender.id = message.sender_user_id
    JOIN users AS recipient ON recipient.id = message.recipient_user_id
    WHERE message.item_id = thread.item_id
      AND (
          (message.sender_user_id = $1 AND message.recipient_user_id = thread.counterpart_user_id)
          OR
          (message.sender_user_id = thread.counterpart_user_id AND message.recipient_user_id = $1)
      )
    ORDER BY message.id DESC
    LIMIT 1
) AS latest ON TRUE
LEFT JOIN LATERAL (
    SELECT count(*)::bigint AS unread_count
    FROM chat_messages AS message
    WHERE message.item_id = thread.item_id
      AND message.sender_user_id = thread.counterpart_user_id
      AND message.recipient_user_id = $1
      AND message.id > COALESCE((
          SELECT read_state.last_read_message_id
          FROM chat_read_states AS read_state
          WHERE read_state.item_id = thread.item_id
            AND read_state.user_id = $1
            AND read_state.counterpart_user_id = thread.counterpart_user_id
      ), 0)
) AS unread ON TRUE
ORDER BY latest.created_at DESC NULLS LAST,
         topic_item.id DESC,
         counterpart.id ASC
`

type ListChatThreadsRow struct {
	ItemID                int64     `json:"item_id"`
	ItemTitle             string    `json:"item_title"`
	ItemImageUrl          string    `json:"item_image_url"`
	CounterpartUserID     int64     `json:"counterpart_user_id"`
	CounterpartUsername   string    `json:"counterpart_username"`
	LastMessageID         int64     `json:"last_message_id"`
	LastOriginChainID     int64     `json:"last_origin_chain_id"`
	LastSenderUserID      int64     `json:"last_sender_user_id"`
	LastSenderUsername    string    `json:"last_sender_username"`
	LastRecipientUserID   int64     `json:"last_recipient_user_id"`
	LastRecipientUsername string    `json:"last_recipient_username"`
	LastClientMessageID   string    `json:"last_client_message_id"`
	LastMessageText       string    `json:"last_message_text"`
	LastMessageCreatedAt  time.Time `json:"last_message_created_at"`
	UnreadCount           int64     `json:"unread_count"`
}

func (q *Queries) ListChatThreads(ctx context.Context, actorID int64) ([]ListChatThreadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatThreads, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatThreadsRow
	for rows.Next() {
		var i ListChatThreadsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemTitle,
			&i.ItemImageUrl,
			&i.CounterpartUserID,
			&i.CounterpartUsername,
			&i.LastMessageID,
			&i.LastOriginChainID,
			&i.LastSenderUserID,
			&i.LastSenderUsername,
			&i.LastRecipientUserID,
			&i.LastRecipientUsername,
			&i.LastClientMessageID,
			&i.LastMessageText,
			&i.LastMessageCreatedAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChatReadState = `-- name: UpsertChatReadState :one
INSERT INTO chat_read_states (
    item_id,
    user_id,
    counterpart_user_id,
    last_read_message_id
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (item_id, user_id, counterpart_user_id) DO UPDATE
SET last_read_message_id = GREATEST(chat_read_states.last_read_message_id, EXCLUDED.last_read_message_id),
    updated_at = now()
RETURNING last_read_message_id
`

type UpsertChatReadStateParams struct {
	ItemID            int64 `json:"item_id"`
	ActorID           int64 `json:"actor_id"`
	CounterpartID     int64 `json:"counterpart_id"`
	LastReadMessageID int64 `json:"last_read_message_id"`
}

func (q *Queries) UpsertChatReadState(ctx context.Context, arg UpsertChatReadStateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertChatReadState,
		arg.ItemID,
		arg.ActorID,
		arg.CounterpartID,
		arg.LastReadMessageID,
	)
	var last_read_message_id int64
	err := row.Scan(&last_read_message_id)
	return last_read_message_id, err
}
