// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package db

import (
	"context"
	"database/sql"

	pgvector_go "github.com/pgvector/pgvector-go"
)

const findSimilarItems = `-- name: FindSimilarItems :many
SELECT candidate_item.id,
       candidate_item.user_id,
       candidate_item.offer_title,
       candidate_item.offer_description,
       candidate_item.want_description,
       candidate_item.offer_category_id,
       candidate_item.want_category_id,
       candidate_item.visual_quality,
       candidate_item.quality_score,
       candidate_item.param_richness,
       candidate_item.is_category_manual,
       candidate_item.image_amount,
       candidate_owner.rating AS user_rating,
       candidate_owner.success_rate AS user_success_rate,
       candidate_item.offer_embedding_local::vector AS offer_embedding_local,
       candidate_item.want_embedding_local::vector AS want_embedding_local,
       (1.0 - (candidate_item.offer_embedding_local <=> source_item.want_embedding_local))::float8 AS similarity
FROM items AS candidate_item
JOIN users AS candidate_owner ON candidate_owner.id = candidate_item.user_id
JOIN items AS source_item ON source_item.id = $1
WHERE candidate_item.id != source_item.id
  AND candidate_item.user_id != source_item.user_id
  AND candidate_item.status = 'MATCHING'
  AND source_item.status = 'MATCHING'
  AND candidate_item.offer_category_id = source_item.want_category_id
ORDER BY candidate_item.offer_embedding_local <=> source_item.want_embedding_local
LIMIT $2
`

type FindSimilarItemsParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

type FindSimilarItemsRow struct {
	ID                  int64               `json:"id"`
	UserID              int64               `json:"user_id"`
	OfferTitle          string              `json:"offer_title"`
	OfferDescription    sql.NullString      `json:"offer_description"`
	WantDescription     sql.NullString      `json:"want_description"`
	OfferCategoryID     sql.NullInt32       `json:"offer_category_id"`
	WantCategoryID      sql.NullInt32       `json:"want_category_id"`
	VisualQuality       sql.NullString      `json:"visual_quality"`
	QualityScore        sql.NullString      `json:"quality_score"`
	ParamRichness       sql.NullString      `json:"param_richness"`
	IsCategoryManual    sql.NullBool        `json:"is_category_manual"`
	ImageAmount         sql.NullInt32       `json:"image_amount"`
	UserRating          sql.NullString      `json:"user_rating"`
	UserSuccessRate     sql.NullString      `json:"user_success_rate"`
	OfferEmbeddingLocal *pgvector_go.Vector `json:"offer_embedding_local"`
	WantEmbeddingLocal  *pgvector_go.Vector `json:"want_embedding_local"`
	Similarity          float64             `json:"similarity"`
}

func (q *Queries) FindSimilarItems(ctx context.Context, arg FindSimilarItemsParams) ([]FindSimilarItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, findSimilarItems, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSimilarItemsRow
	for rows.Next() {
		var i FindSimilarItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OfferTitle,
			&i.OfferDescription,
			&i.WantDescription,
			&i.OfferCategoryID,
			&i.WantCategoryID,
			&i.VisualQuality,
			&i.QualityScore,
			&i.ParamRichness,
			&i.IsCategoryManual,
			&i.ImageAmount,
			&i.UserRating,
			&i.UserSuccessRate,
			&i.OfferEmbeddingLocal,
			&i.WantEmbeddingLocal,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchingSourceItem = `-- name: GetMatchingSourceItem :one
SELECT source_item.id
FROM items AS source_item
WHERE source_item.id = $1
  AND source_item.status = 'MATCHING'
`

func (q *Queries) GetMatchingSourceItem(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMatchingSourceItem, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
