// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ChainStatus string

const (
	ChainStatusPENDING  ChainStatus = "PENDING"
	ChainStatusACCEPTED ChainStatus = "ACCEPTED"
	ChainStatusREJECTED ChainStatus = "REJECTED"
)

func (e *ChainStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainStatus(s)
	case string:
		*e = ChainStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainStatus: %T", src)
	}
	return nil
}

type NullChainStatus struct {
	ChainStatus ChainStatus `json:"chain_status"`
	Valid       bool        `json:"valid"` // Valid is true if ChainStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChainStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainStatus), nil
}

type ParticipantStatus string

const (
	ParticipantStatusWAITING  ParticipantStatus = "WAITING"
	ParticipantStatusAPPROVED ParticipantStatus = "APPROVED"
	ParticipantStatusDECLINED ParticipantStatus = "DECLINED"
)

func (e *ParticipantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantStatus(s)
	case string:
		*e = ParticipantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantStatus: %T", src)
	}
	return nil
}

type NullParticipantStatus struct {
	ParticipantStatus ParticipantStatus `json:"participant_status"`
	Valid             bool              `json:"valid"` // Valid is true if ParticipantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantStatus), nil
}

type Category struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Embedding interface{} `json:"embedding"`
}

type Chain struct {
	ID        int64           `json:"id"`
	Status    NullChainStatus `json:"status"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type ChainItem struct {
	ID         int64                 `json:"id"`
	ChainID    int64                 `json:"chain_id"`
	ItemID     int64                 `json:"item_id"`
	UserID     int64                 `json:"user_id"`
	NextItemID sql.NullInt64         `json:"next_item_id"`
	Status     NullParticipantStatus `json:"status"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

type Item struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	OfferTitle       string         `json:"offer_title"`
	OfferDescription sql.NullString `json:"offer_description"`
	OfferCategory    sql.NullString `json:"offer_category"`
	WantDescription  sql.NullString `json:"want_description"`
	WantCategory     sql.NullString `json:"want_category"`
	OfferEmbedding   interface{}    `json:"offer_embedding"`
	WantEmbedding    interface{}    `json:"want_embedding"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type User struct {
	ID       int64          `json:"id"`
	Username string         `json:"username"`
	Rating   sql.NullString `json:"rating"`
}
