// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignMessageReport = `-- name: AssignMessageReport :exec
UPDATE message_reports
SET assignee_user_id = $1::bigint,
    updated_at = now()
WHERE id = $2
`

type AssignMessageReportParams struct {
	AssigneeID int64 `json:"assignee_id"`
	ReportID   int64 `json:"report_id"`
}

func (q *Queries) AssignMessageReport(ctx context.Context, arg AssignMessageReportParams) error {
	_, err := q.db.ExecContext(ctx, assignMessageReport, arg.AssigneeID, arg.ReportID)
	return err
}

const decideMessageReport = `-- name: DecideMessageReport :execrows
UPDATE message_reports
SET status = $1::report_status,
    decision_comment = $2::text,
    updated_at = now()
WHERE id = $3
  AND status = 'open'
  AND assignee_user_id = $4::bigint
`

type DecideMessageReportParams struct {
	Status          ReportStatus `json:"status"`
	DecisionComment string       `json:"decision_comment"`
	ReportID        int64        `json:"report_id"`
	AssigneeID      int64        `json:"assignee_id"`
}

func (q *Queries) DecideMessageReport(ctx context.Context, arg DecideMessageReportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideMessageReport,
		arg.Status,
		arg.DecisionComment,
		arg.ReportID,
		arg.AssigneeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMessageReportByReporterMessage = `-- name: GetMessageReportByReporterMessage :one
SELECT report.id,
       report.reporter_user_id,
       reporter.username AS reporter_username,
       report.message_id,
       report.reason::text AS reason,
       report.comment,
       report.status::text AS status,
       report.assignee_user_id,
       assignee.username AS assignee_username,
       report.decision_comment,
       report.created_at,
       report.updated_at
FROM message_reports AS report
JOIN users AS reporter ON reporter.id = report.reporter_user_id
LEFT JOIN users AS assignee ON assignee.id = report.assignee_user_id
WHERE report.reporter_user_id = $1
  AND report.message_id = $2
`

type GetMessageReportByReporterMessageParams struct {
	ReporterID int64 `json:"reporter_id"`
	MessageID  int64 `json:"message_id"`
}

type GetMessageReportByReporterMessageRow struct {
	ID               int64          `json:"id"`
	ReporterUserID   int64          `json:"reporter_user_id"`
	ReporterUsername string         `json:"reporter_username"`
	MessageID        int64          `json:"message_id"`
	Reason           string         `json:"reason"`
	Comment          sql.NullString `json:"comment"`
	Status           string         `json:"status"`
	AssigneeUserID   sql.NullInt64  `json:"assignee_user_id"`
	AssigneeUsername sql.NullString `json:"assignee_username"`
	DecisionComment  sql.NullString `json:"decision_comment"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) GetMessageReportByReporterMessage(ctx context.Context, arg GetMessageReportByReporterMessageParams) (GetMessageReportByReporterMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageReportByReporterMessage, arg.ReporterID, arg.MessageID)
	var i GetMessageReportByReporterMessageRow
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.ReporterUsername,
		&i.MessageID,
		&i.Reason,
		&i.Comment,
		&i.Status,
		&i.AssigneeUserID,
		&i.AssigneeUsername,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModerationReport = `-- name: GetModerationReport :one
SELECT report.id,
       report.reporter_user_id,
       reporter.username AS reporter_username,
       report.message_id,
       report.reason::text AS reason,
       report.comment,
       report.status::text AS status,
       report.assignee_user_id,
       assignee.username AS assignee_username,
       report.decision_comment,
       report.created_at,
       report.updated_at
FROM message_reports AS report
JOIN users AS reporter ON reporter.id = report.reporter_user_id
LEFT JOIN users AS assignee ON assignee.id = report.assignee_user_id
WHERE report.id = $1
`

type GetModerationReportRow struct {
	ID               int64          `json:"id"`
	ReporterUserID   int64          `json:"reporter_user_id"`
	ReporterUsername string         `json:"reporter_username"`
	MessageID        int64          `json:"message_id"`
	Reason           string         `json:"reason"`
	Comment          sql.NullString `json:"comment"`
	Status           string         `json:"status"`
	AssigneeUserID   sql.NullInt64  `json:"assignee_user_id"`
	AssigneeUsername sql.NullString `json:"assignee_username"`
	DecisionComment  sql.NullString `json:"decision_comment"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) GetModerationReport(ctx context.Context, reportID int64) (GetModerationReportRow, error) {
	row := q.db.QueryRowContext(ctx, getModerationReport, reportID)
	var i GetModerationReportRow
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.ReporterUsername,
		&i.MessageID,
		&i.Reason,
		&i.Comment,
		&i.Status,
		&i.AssigneeUserID,
		&i.AssigneeUsername,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessageReport = `-- name: InsertMessageReport :one
INSERT INTO message_reports (reporter_user_id, message_id, reason, comment)
VALUES (
    $1,
    $2,
    $3::report_reason,
    $4
)
ON CONFLICT (reporter_user_id, message_id) DO NOTHING
RETURNING id
`

type InsertMessageReportParams struct {
	ReporterID int64          `json:"reporter_id"`
	MessageID  int64          `json:"message_id"`
	Reason     ReportReason   `json:"reason"`
	Comment    sql.NullString `json:"comment"`
}

func (q *Queries) InsertMessageReport(ctx context.Context, arg InsertMessageReportParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMessageReport,
		arg.ReporterID,
		arg.MessageID,
		arg.Reason,
		arg.Comment,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listMessageReports = `-- name: ListMessageReports :many
SELECT report.id,
       report.reporter_user_id,
       reporter.username AS reporter_username,
       report.message_id,
       report.reason::text AS reason,
       report.comment,
       report.status::text AS status,
       report.assignee_user_id,
       assignee.username AS assignee_username,
       report.decision_comment,
       report.created_at,
       report.updated_at
FROM message_reports AS report
JOIN users AS reporter ON reporter.id = report.reporter_user_id
LEFT JOIN users AS assignee ON assignee.id = report.assignee_user_id
WHERE report.id > $1
  AND ($2::text = '' OR report.status::text = $2::text)
  AND ($3::text = '' OR report.reason::text = $3::text)
  AND (NOT $4::boolean OR report.assignee_user_id IS NULL)
  AND ($5::bigint = 0 OR report.assignee_user_id = $5::bigint)
ORDER BY report.id
LIMIT $6
`

type ListMessageReportsParams struct {
	AfterID    int64  `json:"after_id"`
	Status     string `json:"status"`
	Reason     string `json:"reason"`
	Unassigned bool   `json:"unassigned"`
	AssigneeID int64  `json:"assignee_id"`
	PageSize   int32  `json:"page_size"`
}

type ListMessageReportsRow struct {
	ID               int64          `json:"id"`
	ReporterUserID   int64          `json:"reporter_user_id"`
	ReporterUsername string         `json:"reporter_username"`
	MessageID        int64          `json:"message_id"`
	Reason           string         `json:"reason"`
	Comment          sql.NullString `json:"comment"`
	Status           string         `json:"status"`
	AssigneeUserID   sql.NullInt64  `json:"assignee_user_id"`
	AssigneeUsername sql.NullString `json:"assignee_username"`
	DecisionComment  sql.NullString `json:"decision_comment"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

func (q *Queries) ListMessageReports(ctx context.Context, arg ListMessageReportsParams) ([]ListMessageReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessageReports,
		arg.AfterID,
		arg.Status,
		arg.Reason,
		arg.Unassigned,
		arg.AssigneeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageReportsRow
	for rows.Next() {
		var i ListMessageReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterUserID,
			&i.ReporterUsername,
			&i.MessageID,
			&i.Reason,
			&i.Comment,
			&i.Status,
			&i.AssigneeUserID,
			&i.AssigneeUsername,
			&i.DecisionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT message.id,
       message.chain_id,
       sender.id AS sender_user_id,
       sender.username AS sender_username,
       recipient.id AS recipient_user_id,
       recipient.username AS recipient_username,
       message.client_message_id,
       message.message_text,
       message.created_at
FROM chat_messages AS message
JOIN users AS sender ON sender.id = message.sender_user_id
JOIN users AS recipient ON recipient.id = message.recipient_user_id
WHERE message.chain_id = $1
  AND (
      (message.sender_user_id = $2 AND message.recipient_user_id = $3)
      OR
      (message.sender_user_id = $3 AND message.recipient_user_id = $2)
  )
ORDER BY message.id ASC
`

type ListThreadMessagesParams struct {
	ChainID      int64 `json:"chain_id"`
	FirstUserID  int64 `json:"first_user_id"`
	SecondUserID int64 `json:"second_user_id"`
}

type ListThreadMessagesRow struct {
	ID                int64     `json:"id"`
	ChainID           int64     `json:"chain_id"`
	SenderUserID      int64     `json:"sender_user_id"`
	SenderUsername    string    `json:"sender_username"`
	RecipientUserID   int64     `json:"recipient_user_id"`
	RecipientUsername string    `json:"recipient_username"`
	ClientMessageID   string    `json:"client_message_id"`
	MessageText       string    `json:"message_text"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) ListThreadMessages(ctx context.Context, arg ListThreadMessagesParams) ([]ListThreadMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listThreadMessages, arg.ChainID, arg.FirstUserID, arg.SecondUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadMessagesRow
	for rows.Next() {
		var i ListThreadMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.SenderUserID,
			&i.SenderUsername,
			&i.RecipientUserID,
			&i.RecipientUsername,
			&i.ClientMessageID,
			&i.MessageText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMessageReport = `-- name: LockMessageReport :one
SELECT report.id,
       report.status::text AS status,
       report.assignee_user_id
FROM message_reports AS report
WHERE report.id = $1
FOR UPDATE
`

type LockMessageReportRow struct {
	ID             int64         `json:"id"`
	Status         string        `json:"status"`
	AssigneeUserID sql.NullInt64 `json:"assignee_user_id"`
}

func (q *Queries) LockMessageReport(ctx context.Context, reportID int64) (LockMessageReportRow, error) {
	row := q.db.QueryRowContext(ctx, lockMessageReport, reportID)
	var i LockMessageReportRow
	err := row.Scan(&i.ID, &i.Status, &i.AssigneeUserID)
	return i, err
}
