// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	pgvector_go "github.com/pgvector/pgvector-go"
)

type ChainStatus string

const (
	ChainStatusPENDING  ChainStatus = "PENDING"
	ChainStatusACCEPTED ChainStatus = "ACCEPTED"
	ChainStatusREJECTED ChainStatus = "REJECTED"
)

func (e *ChainStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainStatus(s)
	case string:
		*e = ChainStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainStatus: %T", src)
	}
	return nil
}

type NullChainStatus struct {
	ChainStatus ChainStatus `json:"chain_status"`
	Valid       bool        `json:"valid"` // Valid is true if ChainStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChainStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainStatus), nil
}

type ItemStatus string

const (
	ItemStatusANALYZING ItemStatus = "ANALYZING"
	ItemStatusMATCHING  ItemStatus = "MATCHING"
	ItemStatusLOCKED    ItemStatus = "LOCKED"
)

func (e *ItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatus(s)
	case string:
		*e = ItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatus: %T", src)
	}
	return nil
}

type NullItemStatus struct {
	ItemStatus ItemStatus `json:"item_status"`
	Valid      bool       `json:"valid"` // Valid is true if ItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatus), nil
}

type ParticipantStatus string

const (
	ParticipantStatusWAITING  ParticipantStatus = "WAITING"
	ParticipantStatusAPPROVED ParticipantStatus = "APPROVED"
	ParticipantStatusDECLINED ParticipantStatus = "DECLINED"
)

func (e *ParticipantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantStatus(s)
	case string:
		*e = ParticipantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantStatus: %T", src)
	}
	return nil
}

type NullParticipantStatus struct {
	ParticipantStatus ParticipantStatus `json:"participant_status"`
	Valid             bool              `json:"valid"` // Valid is true if ParticipantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantStatus), nil
}

type Category struct {
	ID             int32       `json:"id"`
	Name           string      `json:"name"`
	EmbeddingLocal interface{} `json:"embedding_local"`
}

type Chain struct {
	ID        int64       `json:"id"`
	Status    ChainStatus `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	ExpiresAt time.Time   `json:"expires_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type ChainItem struct {
	ID         int64             `json:"id"`
	ChainID    int64             `json:"chain_id"`
	ItemID     int64             `json:"item_id"`
	UserID     int64             `json:"user_id"`
	NextItemID sql.NullInt64     `json:"next_item_id"`
	Status     ParticipantStatus `json:"status"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

type Item struct {
	ID                  int64          `json:"id"`
	UserID              int64          `json:"user_id"`
	OfferTitle          string         `json:"offer_title"`
	OfferDescription    sql.NullString `json:"offer_description"`
	OfferCategoryID     sql.NullInt32  `json:"offer_category_id"`
	WantDescription     sql.NullString `json:"want_description"`
	WantCategoryID      sql.NullInt32  `json:"want_category_id"`
	VisualQuality       sql.NullString `json:"visual_quality"`
	QualityScore        sql.NullString `json:"quality_score"`
	ParamRichness       sql.NullString `json:"param_richness"`
	IsCategoryManual    sql.NullBool   `json:"is_category_manual"`
	ImageAmount         sql.NullInt32  `json:"image_amount"`
	OfferEmbeddingLocal interface{}    `json:"offer_embedding_local"`
	WantEmbeddingLocal  interface{}    `json:"want_embedding_local"`
	Status              NullItemStatus `json:"status"`
	LastStatusUpdatedAt sql.NullTime   `json:"last_status_updated_at"`
	CreatedAt           sql.NullTime   `json:"created_at"`
}

type User struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	Rating      sql.NullString `json:"rating"`
	SuccessRate sql.NullString `json:"success_rate"`
}
