// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	ClaimStaleAnalyzingItems(ctx context.Context, arg ClaimStaleAnalyzingItemsParams) ([]int64, error)
	CompleteItemAnalysis(ctx context.Context, arg CompleteItemAnalysisParams) (int64, error)
	FindCategory(ctx context.Context, arg FindCategoryParams) ([]FindCategoryRow, error)
	FindSimilarItems(ctx context.Context, arg FindSimilarItemsParams) ([]FindSimilarItemsRow, error)
	GetItemForAnalysis(ctx context.Context, id int64) (GetItemForAnalysisRow, error)
	GetMatchingSourceItem(ctx context.Context, id int64) (GetMatchingSourceItemRow, error)
}

var _ Querier = (*Queries)(nil)
