// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tagging.sql

package db

import (
	"context"

	pgvector_go "github.com/pgvector/pgvector-go"
)

const countCategories = `-- name: CountCategories :one
SELECT count(*)
FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesMissingEmbedding = `-- name: CountCategoriesMissingEmbedding :one
SELECT count(*)
FROM categories
WHERE embedding_local IS NULL
`

func (q *Queries) CountCategoriesMissingEmbedding(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesMissingEmbedding)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findCategory = `-- name: FindCategory :many
SELECT category.id,
       category.name,
       (1.0 - (category.embedding_local <=> $1::vector))::float8 AS similarity
FROM categories AS category
WHERE category.embedding_local IS NOT NULL
ORDER BY category.embedding_local <=> $1::vector
LIMIT 2
`

type FindCategoryRow struct {
	ID         int32   `json:"id"`
	Name       string  `json:"name"`
	Similarity float64 `json:"similarity"`
}

func (q *Queries) FindCategory(ctx context.Context, embeddingLocal pgvector_go.Vector) ([]FindCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, findCategory, embeddingLocal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCategoryRow
	for rows.Next() {
		var i FindCategoryRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Similarity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesMissingEmbedding = `-- name: ListCategoriesMissingEmbedding :many
SELECT category.id, category.name
FROM categories AS category
WHERE category.embedding_local IS NULL
ORDER BY category.id
`

type ListCategoriesMissingEmbeddingRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListCategoriesMissingEmbedding(ctx context.Context) ([]ListCategoriesMissingEmbeddingRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesMissingEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesMissingEmbeddingRow
	for rows.Next() {
		var i ListCategoriesMissingEmbeddingRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryEmbedding = `-- name: SetCategoryEmbedding :execrows
UPDATE categories
SET embedding_local = $1::vector
WHERE id = $2
  AND embedding_local IS NULL
`

type SetCategoryEmbeddingParams struct {
	EmbeddingLocal pgvector_go.Vector `json:"embedding_local"`
	ID             int32              `json:"id"`
}

func (q *Queries) SetCategoryEmbedding(ctx context.Context, arg SetCategoryEmbeddingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCategoryEmbedding, arg.EmbeddingLocal, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
