// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tagging.sql

package db

import (
	"context"

	pgvector_go "github.com/pgvector/pgvector-go"
)

const findCategory = `-- name: FindCategory :many
SELECT id, name, (1.0 - (embedding <=> $1::vector))::float8 AS similarity
FROM categories
ORDER BY embedding <=> $1::vector
LIMIT 2
`

type FindCategoryRow struct {
	ID         int32   `json:"id"`
	Name       string  `json:"name"`
	Similarity float64 `json:"similarity"`
}

func (q *Queries) FindCategory(ctx context.Context, embedding pgvector_go.Vector) ([]FindCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, findCategory, embedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCategoryRow
	for rows.Next() {
		var i FindCategoryRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Similarity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
