// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"
	"database/sql"

	pgvector_go "github.com/pgvector/pgvector-go"
)

const claimStaleAnalyzingItems = `-- name: ClaimStaleAnalyzingItems :many
WITH stale_items AS (
    SELECT item.id
    FROM items AS item
    WHERE item.status = 'ANALYZING'
      AND item.last_status_updated_at < $1
    ORDER BY item.last_status_updated_at, item.id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE items AS claimed_item
SET last_status_updated_at = NOW()
FROM stale_items
WHERE claimed_item.id = stale_items.id
RETURNING claimed_item.id
`

type ClaimStaleAnalyzingItemsParams struct {
	StaleBefore sql.NullTime `json:"stale_before"`
	BatchSize   int32        `json:"batch_size"`
}

func (q *Queries) ClaimStaleAnalyzingItems(ctx context.Context, arg ClaimStaleAnalyzingItemsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, claimStaleAnalyzingItems, arg.StaleBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeItemAnalysis = `-- name: CompleteItemAnalysis :execrows
UPDATE items
SET offer_category_id = $1,
    want_category_id = $2,
    param_richness = $3,
    is_category_manual = $4,
    offer_embedding_local = $5::vector,
    want_embedding_local = $6::vector,
    status = 'MATCHING',
    last_status_updated_at = NOW()
WHERE id = $7
  AND status = 'ANALYZING'
`

type CompleteItemAnalysisParams struct {
	OfferCategoryID     sql.NullInt32       `json:"offer_category_id"`
	WantCategoryID      sql.NullInt32       `json:"want_category_id"`
	ParamRichness       sql.NullString      `json:"param_richness"`
	IsCategoryManual    sql.NullBool        `json:"is_category_manual"`
	OfferEmbeddingLocal *pgvector_go.Vector `json:"offer_embedding_local"`
	WantEmbeddingLocal  *pgvector_go.Vector `json:"want_embedding_local"`
	ID                  int64               `json:"id"`
}

func (q *Queries) CompleteItemAnalysis(ctx context.Context, arg CompleteItemAnalysisParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeItemAnalysis,
		arg.OfferCategoryID,
		arg.WantCategoryID,
		arg.ParamRichness,
		arg.IsCategoryManual,
		arg.OfferEmbeddingLocal,
		arg.WantEmbeddingLocal,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getItemForAnalysis = `-- name: GetItemForAnalysis :one
SELECT item.id,
       item.offer_title,
       item.offer_description,
       item.want_description,
       item.status
FROM items AS item
WHERE item.id = $1
`

type GetItemForAnalysisRow struct {
	ID               int64          `json:"id"`
	OfferTitle       string         `json:"offer_title"`
	OfferDescription sql.NullString `json:"offer_description"`
	WantDescription  sql.NullString `json:"want_description"`
	Status           NullItemStatus `json:"status"`
}

func (q *Queries) GetItemForAnalysis(ctx context.Context, id int64) (GetItemForAnalysisRow, error) {
	row := q.db.QueryRowContext(ctx, getItemForAnalysis, id)
	var i GetItemForAnalysisRow
	err := row.Scan(
		&i.ID,
		&i.OfferTitle,
		&i.OfferDescription,
		&i.WantDescription,
		&i.Status,
	)
	return i, err
}
