// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"
	"database/sql"
	"time"

	pgvector_go "github.com/pgvector/pgvector-go"
)

const claimStaleAnalyzingItems = `-- name: ClaimStaleAnalyzingItems :many
WITH stale_items AS (
    SELECT item.id
    FROM items AS item
    WHERE item.status = 'ANALYZING'
      AND item.last_status_updated_at < $1
    ORDER BY item.last_status_updated_at, item.id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE items AS claimed_item
SET last_status_updated_at = NOW()
FROM stale_items
WHERE claimed_item.id = stale_items.id
RETURNING claimed_item.id
`

type ClaimStaleAnalyzingItemsParams struct {
	StaleBefore time.Time `json:"stale_before"`
	BatchSize   int32     `json:"batch_size"`
}

func (q *Queries) ClaimStaleAnalyzingItems(ctx context.Context, arg ClaimStaleAnalyzingItemsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, claimStaleAnalyzingItems, arg.StaleBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeItemAnalysis = `-- name: CompleteItemAnalysis :execrows
WITH analyzed_item AS (
    UPDATE items
    SET offer_category_id = $1,
        param_richness = $2,
        is_category_manual = $3,
        offer_embedding_local = $4::vector,
        offer_embedding_external = $5::vector,
        status = 'MATCHING',
        last_status_updated_at = NOW()
    WHERE id = $6
      AND status = 'ANALYZING'
      AND analysis_version = $7
    RETURNING id
)
INSERT INTO matching_jobs (
    item_id,
    status,
    attempts,
    available_at,
    locked_at,
    last_error,
    updated_at
)
SELECT id, 'PENDING', 0, NOW(), NULL, NULL, NOW()
FROM analyzed_item
ON CONFLICT (item_id) DO UPDATE
SET status = 'PENDING',
    attempts = 0,
    available_at = NOW(),
    locked_at = NULL,
    last_error = NULL,
    updated_at = NOW()
`

type CompleteItemAnalysisParams struct {
	OfferCategoryID        sql.NullInt32       `json:"offer_category_id"`
	ParamRichness          sql.NullString      `json:"param_richness"`
	IsCategoryManual       bool                `json:"is_category_manual"`
	OfferEmbeddingLocal    *pgvector_go.Vector `json:"offer_embedding_local"`
	OfferEmbeddingExternal *pgvector_go.Vector `json:"offer_embedding_external"`
	ID                     int64               `json:"id"`
	AnalysisVersion        int64               `json:"analysis_version"`
}

func (q *Queries) CompleteItemAnalysis(ctx context.Context, arg CompleteItemAnalysisParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeItemAnalysis,
		arg.OfferCategoryID,
		arg.ParamRichness,
		arg.IsCategoryManual,
		arg.OfferEmbeddingLocal,
		arg.OfferEmbeddingExternal,
		arg.ID,
		arg.AnalysisVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getItemForAnalysis = `-- name: GetItemForAnalysis :one
SELECT item.id,
       item.offer_title,
       item.offer_description,
       item.status,
       item.analysis_version
FROM items AS item
WHERE item.id = $1
`

type GetItemForAnalysisRow struct {
	ID               int64          `json:"id"`
	OfferTitle       string         `json:"offer_title"`
	OfferDescription sql.NullString `json:"offer_description"`
	Status           ItemStatus     `json:"status"`
	AnalysisVersion  int64          `json:"analysis_version"`
}

func (q *Queries) GetItemForAnalysis(ctx context.Context, id int64) (GetItemForAnalysisRow, error) {
	row := q.db.QueryRowContext(ctx, getItemForAnalysis, id)
	var i GetItemForAnalysisRow
	err := row.Scan(
		&i.ID,
		&i.OfferTitle,
		&i.OfferDescription,
		&i.Status,
		&i.AnalysisVersion,
	)
	return i, err
}

const getItemWishesForAnalysis = `-- name: GetItemWishesForAnalysis :many
SELECT id, item_id, want_description
FROM item_wishes
WHERE item_id = $1
`

type GetItemWishesForAnalysisRow struct {
	ID              int64  `json:"id"`
	ItemID          int64  `json:"item_id"`
	WantDescription string `json:"want_description"`
}

func (q *Queries) GetItemWishesForAnalysis(ctx context.Context, itemID int64) ([]GetItemWishesForAnalysisRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemWishesForAnalysis, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemWishesForAnalysisRow
	for rows.Next() {
		var i GetItemWishesForAnalysisRow
		if err := rows.Scan(&i.ID, &i.ItemID, &i.WantDescription); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemWishAnalysis = `-- name: UpdateItemWishAnalysis :exec
UPDATE item_wishes
SET want_category_id = $2,
    want_embedding_local = $3::vector,
    want_embedding_external = $4::vector
WHERE id = $1
`

type UpdateItemWishAnalysisParams struct {
	ID                    int64               `json:"id"`
	WantCategoryID        sql.NullInt32       `json:"want_category_id"`
	WantEmbeddingLocal    *pgvector_go.Vector `json:"want_embedding_local"`
	WantEmbeddingExternal *pgvector_go.Vector `json:"want_embedding_external"`
}

func (q *Queries) UpdateItemWishAnalysis(ctx context.Context, arg UpdateItemWishAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, updateItemWishAnalysis,
		arg.ID,
		arg.WantCategoryID,
		arg.WantEmbeddingLocal,
		arg.WantEmbeddingExternal,
	)
	return err
}
